# Generated by Django 5.1.2 on 2025-06-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PF_App', '0002_faqquestion_contactmessage_best_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
    ]
